### ISSUE TITLE
0.4.3 Segmentation fault (core dumped) 0.4.2 work

### ISSUE THREAD

**Issue by as296** [todxx/teamredminer#47] opened 2019-04-03 13:56 UTC
![notwork](https://user-images.githubusercontent.com/6040315/55484834-e660ca80-5631-11e9-99bf-8cf500ca11a5.png)
what to do?
This issue is on motherboards with an AMD CPU only

**Comment by todxx** [comment] 2019-04-03 21:49
Well that is rather strange.  Can you run the version that segfaults again with `--debug`?

**Comment by as296** [comment] 2019-04-03 22:54
![роро1](https://user-images.githubusercontent.com/6040315/55518402-89d6cd00-567c-11e9-9c57-181a26ce35cf.png)

**Comment by todxx** [comment] 2019-04-05 00:54
Thanks for running that, at least now we know it's something that's happening before we even get to gpu initialization.  We'll review the changes in 0.4.3 and see if we can find what is causing this.

**Comment by todxx** [comment] 2019-04-05 00:59
Actually, could I ask you for one more test?  Could you run the 0.4.3 version again under strace, such as `strace -o strace.log ./teamredminer ...` and either post or somehow send me the strace.log file?

**Comment by as296** [comment] 2019-04-05 10:33
[strace.log](https://github.com/todxx/teamredminer/files/3047470/strace.log)

**Comment by as296** [comment] 2019-04-07 12:54
did the log help?

**Comment by todxx** [comment] 2019-04-08 06:18
Sorry for not responding sooner, yes the log helped.  Thank you for taking the time to collect and post it.  Unfortunately we still haven't been able to identify exactly where the problem is since we cannot seem to reproduce it, but we're still working on it.  We're just a bit busy at the moment.

**Comment by todxx** [comment] 2019-04-08 07:41
If you have time, there's one more thing you could do that would be very helpful, and that is to run the miner under gdb and post where the segfault is happening.

You'll want to start the miner under gdb by running the following: `gdb --args ./teamredminer ...`
Once gdb starts, it'll wait for commands before doing anything.
You'll first want to switch to asm mode by typing `layout asm`.
Next you'll want to run the miner by typing `run`.

GDB will now run the miner and should catch the segfault signal and show which instruction generated it.  
Once that happens, if you could post either a screen shot or a text paste of the screen that would be great.

At this point you can type `quit` into gdb to close it.  It may ask to confirm the action, and you'll need to press `y` to close it.

**Comment by as296** [comment] 2019-04-08 12:10
When launched using GDB TRM v0.4.3, it starts up normally and works.
There are other options to catch the error?

**Comment by maktan38** [comment] 2019-04-08 18:58
for turtle
4gb rx570 8.100 khash (hynix)
8gb rx570 7.500 khash (hynix)
 Why does 8gb gpu hash give less  than 4gb? I changed the strap , but the hashrate didn't rise. 
Sorry my english.

**Comment by as296** [comment] 2019-04-09 06:22
> for turtle
> 4gb rx570 8.100 khash (hynix)
> 8gb rx570 7.500 khash (hynix)
> Why does 8gb gpu hash give less than 4gb? I changed the strap , but the hashrate didn't rise.
> Sorry my english.
here what are you writing here? create a separate topic

**Comment by as296** [comment] 2019-04-09 06:23
> for turtle
> 4gb rx570 8.100 khash (hynix)
> 8gb rx570 7.500 khash (hynix)
> Why does 8gb gpu hash give less than 4gb? I changed the strap , but the hashrate didn't rise.
> Sorry my english.

here what are you writing here? create a separate topic

**Comment by todxx** [comment] 2019-04-09 12:41
@maktan38 please open a new issue with your questions.

@as296 If the segfault does not appear when running under gdb, it implies there is a threading synchronization problem.  These can be rather difficult to reproduce and debug.  The most helpful thing you could provide us right now would be the core dump, but this will usually be a very large file.

**Comment by as296** [comment] 2019-04-09 14:12
> @as296 If the segfault does not appear when running under gdb, it implies there is a threading synchronization problem. These can be rather difficult to reproduce and debug. The most helpful thing you could provide us right now would be the core dump, but this will usually be a very large file.




[_usr_bin_strace.0.crash.log](https://github.com/todxx/teamredminer/files/3059401/_usr_bin_strace.0.crash.log)
Is this what you need?

**Comment by todxx** [comment] 2019-04-10 08:29
@as296 Very close, that seems to be a dump of when you ran the miner under strace, can you grab a dump of just running the miner alone?

**Comment by as296** [comment] 2019-04-10 10:49
[core.teamredminer.zip](https://github.com/todxx/teamredminer/files/3063360/core.teamredminer.zip)
this is it?

**Comment by as296** [comment] 2019-04-13 06:44
> @as296 Very close, that seems to be a dump of when you ran the miner under strace, can you grab a dump of just running the miner alone?

How is it going?

**Comment by cooperalex78** [comment] 2019-04-23 06:16
I have the same problem on the 4.3 and 4.4 versions, the segmentation fault, through the gdb it's working.

**Comment by scallyob** [comment] 2019-04-28 03:08
Same here. Seg fault on 4.4, last working version I had was 4.0 (haven't tried others). Running through gdb seems to work fine.

**Comment by as296** [comment] 2019-04-29 08:21
This situation occurs on motherboard with AMD cpu!!!

**Comment by mrAbS777** [comment] 2019-06-07 22:18
ll try to provide some additional info. 
have got the same problem on AM3 motherboard with FX-8320 . Working smoothly through gdb. And segfault without. 

As opposite on AM4 mobos with Ryzens no troubles at all.  

Versions from 0.4.5 till 0.5.1 no differences.

**Comment by todxx** [comment] 2019-09-25 23:24
Closing old issue.  If you're still having these problems with the newer releases, please open a new issue.

**Closed by todxx** 2019-09-25 23:24 UTC
